version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8501:8501"  # or adjust to your app’s port
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=postgresql
      - DB_PASSWORD=postgresql

volumes:
  db_data:
